apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: web-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-browser
  template:
    metadata:
      labels:
        app: web-browser
    spec:
      containers:
        # VNC Container
        - name: vnc
          image: vaibhavx7/web-browser:latest
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi" 
          ports:
          - containerPort: 5900
          args:
            - bash
            - -c
            - |
              ./start_vnc.sh && tail -f /dev/null
          env:
            - name: VNC_PASSWORD
              value: "vaibhav"
          securityContext:
              privileged: true
          stdin: true
          tty: true
        # Katalon Android Container
        - name: web-browser
          image: vaibhavx7/web-browser:latest
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "8Gi" 
          ports:
          - containerPort: 5901
          args:
            - bash
            - -c
            - |
              ./emulator_headed_mode.sh && tail -f /dev/null
          env:
            - name: APPIUM_PORT
              value: "4725"
            - name: VNC_PASSWORD
              value: "vaibhav"
          securityContext:
              privileged: true
          stdin: true
          tty: true
