FROM eclipse-temurin:8-jdk

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

SHELL ["/bin/bash", "-c"]   

RUN apt update && apt install -y curl sudo wget unzip libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libnss3 libxcursor1 libpulse-dev libxshmfence-dev xauth xvfb x11vnc fluxbox wmctrl libdbus-glib-1-2 bzip2

ARG KATALON_VERSION="8.6.9"
ARG KATALON_REPORT_PATH="/empresa/Reports/."
ARG KATALON_LOCAL_REPORT_PATH="/home/siddhatech/Reports"
ARG TEST_SUITE
ARG TYPE_OF_TEST
ARG EXEC_PROFILE
ARG PROJECT_NAME
ARG API_KEY

ENV KATALON_JAVA_HOME=/opt/java/openjdk/jre
ENV KATALON_REPORT_PATH="/empresa/Reports/."
ENV KATALON_LOCAL_REPORT_PATH="/home/siddhatech/Reports"
ENV DOCKER="true"
ENV DISPLAY=:1
ENV KATALON_VERSION=$KATALON_VERSION
ENV TEST_SUITE_NAME=$TEST_SUITE
ENV TYPE_OF_TEST=$TYPE_OF_TEST
ENV EXEC_PROFILE=$EXEC_PROFILE
ENV PROJECT_NAME=$PROJECT_NAME
ENV API_KEY=$API_KEY

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash && \
    apt-get install -y nodejs && \
    npm install -g appium@1.22.3 && \
    exit 0 && \
    npm cache clean && \
    apt-get remove --purge -y npm && \  
    apt-get autoremove --purge -y && \
    apt-get clean && \
    rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*

RUN wget https://download.katalon.com/${KATALON_VERSION}/Katalon_Studio_Engine_Linux_64-${KATALON_VERSION}.tar.gz && \
    tar -xvzf Katalon_Studio_Engine_Linux_64-${KATALON_VERSION}.tar.gz && \
    rm -rf Katalon_Studio_Engine_Linux_64-${KATALON_VERSION}.tar.gz

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb

COPY . /

RUN chmod a+x web_headed_mode.sh && \
    chmod a+x web_headless_mode.sh && \
    chmod a+x start_vnc.sh && \
    chmod 777 portforward_vnc.sh && \
    chmod 777 delete_pod.sh

CMD [ "/bin/bash" ]
