version: "3"
services:
# Launch Web tests and appium instance
  web-service:
    image: web-browser
    build:
      dockerfile: Dockerfile_Web

    ports:
      - 4725:4725
    container_name: web
    depends_on:
      - VNC-Service
    environment:
      - APPIUM_PORT=4725
    privileged: true
    command:
      - bash
      - -c
      - | 
         ./web_headed_mode.sh
         tail -f /dev/null
    tty: true
    stdin_open: true
# Starting VNC server
  VNC-Service:
    image: web-browser
    build:
      dockerfile: Dockerfile_Web
    ports:
      - 5901:5901
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: vaibhav
    privileged: true
    command:
      - bash
      - -c
      - |
        ./start_vnc.sh
         tail -f /dev/null
    tty: true
    stdin_open: true
